name=Arduino_SE05X
version=0.0.1
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Arduino Library for the NXP SE05X crypto chips
paragraph=
category=Communication
url=https://github.com/arduino-libraries/Arduino_SE05X/
architectures=renesas_portenta,zephyr_main,mbed_portenta
